### ISSUE TITLE
Display Information

### ISSUE THREAD

**Issue by andey-robins** [andeyt/hashproject#3]
Devise a system so that when the user requests that the data be printed, it will be. Write the printing in a function with the tag,

`void displayData(vector<DataEntry> const & data);`

All of the printing is to be performed in this function.

**Comment by jayfeather31** [comment]
I'll need to know exactly what you need printed, or rather, what variables I'll need to bounce this off of. This will largely come from Jeremiah or yourself, as currently, I can only really begin to start a prototype function that takes in input without knowing what variables to print.

**Comment by andey-robins** [comment]
Ah yes, we're looking to do a full print of all the data that is present in the tree. Issue #1 talks about what format the getters and setters for each `DataEntry` will be.

For instance, so print the ID of node `i`,
`cout << data[i].getId() << endl;`

The print function should iterate through each item in the tree, printing out all of the data from each element.

**Comment by jayfeather31** [comment]
Okay, that shouldn't necessarily be a problem. I'll wait for those functions to get finished, but I appreciate you responding this quickly. I'll attempt to make a prototype and get back to you, though I'm not sure when I'll get this finished due to other assignments.

**Comment by andey-robins** [comment]
Take your time, and even if those functions aren't finished, feel free to write your segment whenever you have time.

**Comment by Vaskis** [comment]
I will be posting My current version of the class soon. It has all of the Item's and they all seem to be functioning. The only issue I have is if you Andey need any constructors beyond DataEntry = default, if so I don't know if I can help with that as it depends upon how all of the recursion and stuff works.

My code also includes a simple print functions and an empty checker that checks "Event" to see if it is an empty string. I will be working on the vector/tree expansion thing now and see if I can get anywhere with that.

Most of the code stuff I will post will have the basic code and an int main() that tests it and shows how it works. See you guys Monday!

**Comment by andey-robins** [comment]
I'm going to assign this task to myself and begin implementing the printing as described in the project details.

**Comment by andey-robins** [comment]
Task finished in latest commit. Closing this issue.
