### ISSUE TITLE
User Input

### ISSUE THREAD

**Issue by andey-robins** [andeyt/hashproject#6]
Validate the user input in order to interpret what the user wants the program to do. Reference https://github.com/andeyt/bloodsugar/blob/master/bloodsugar.cpp for an example of how to do this. Build an if-elseif-else block for the commands:
- insert
- visualize
- exit

**Comment by jayfeather31** [comment]
Just an FYI, I will only be able to go ahead and establish a prototype function for this, as I lack further information on how the data structure will necessarily take the entry. I can't say I'll be able to get to it today as of this post, but it is something I thought you deserved to know.

**Comment by andey-robins** [comment]
No worries, this is just framework for the next week or two of work. All that this issue needs to do is properly branch through user inputs. I will handle the actual handshaking between the data structure and the input loop.

**Comment by jayfeather31** [comment]
Okay, I just wanted to make sure you knew, but more than likely, this'll be a collection of stubs that takes in data and stores it, but doesn't necessarily pass it on.

**Comment by andey-robins** [comment]
That's perfect, just what we need. I'll connect the stubs to bring everything into a cohesive project

**Comment by andey-robins** [comment]
Addressed in latest commit. Closing this issue.
